packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '0': '@prisma/client'
  '1': '@prisma/engines'
  '2': esbuild
  '3': prisma
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
